### ISSUE TITLE
Intersection of multi-union polygons returns empty polygons

### ISSUE THREAD

**Issue by mcara** [spacetelescope/sphere#74] opened 2016-05-05 16:27 UTC
When a polygon is formed by creating a union between two polygons, the intersection of this "larger" polygon even with itself produces an empty polygon (meaning that the polygon does not intersect with itself).

Here is an example that illustrates the issue:
```python
>>> from stsci.sphere.polygon import SphericalPolygon
>>> s1 = SphericalPolygon.from_radec(np.array([150.15056635,  150.18472797,  150.18472641, 150.15056557, 150.15056635]), np.array([2.33675579,  2.33675454,  2.30262137,  2.3026226 ,  2.33675579]))
>>> s2 = SphericalPolygon.from_radec(np.array([150.18472955,  150.18472798,  150.15056635, 150.15056714, 150.18472955]), np.array([2.37105428,  2.33692121,  2.33692245,  2.37105554,  2.37105428]))
>>> s12 = s2.union(s1)  # create a union polygon
>>> list(s12.to_radec())
[(array([ 150.15056714,  150.18472955,  150.18472798,  150.15056635, 150.15056714]),
  array([ 2.37105554,  2.37105428,  2.33692121,  2.33692245,  2.37105554])),
 (array([ 150.18472797,  150.18472641,  150.15056557,  150.15056635, 150.18472797]),
  array([ 2.33675454,  2.30262137,  2.3026226 ,  2.33675579,  2.33675454]))]
>>> s12.area()
7.0980334054837613e-07
>>>
>>> # Now intersect s12 with itself:
>>> s12int = s12.intersection(s12)
>>> list(s12int.to_radec())
[]
>>> s12int.area()
0.0
```

CC: @stsci-hack

**Comment by mcara** [comment] 2016-05-18 19:59
Is there anybody out there?

**Comment by pllim** [comment] 2016-05-18 20:01
Yes, but I think this is @bernie-simon's turf?

**Comment by mcara** [comment] 2016-05-18 20:03
I know, but I did not expect that I have to prefix ``sphere`` issues with @bernie-simon

**Comment by mcara** [comment] 2016-05-18 20:03
We should not invoke you know who's handle again: http://www.chacha.com/question/what-event-will-occur-if-i-repeat-the-name-beetle-juice-three-consecutive-times

**Comment by pllim** [comment] 2016-05-18 20:05
He-Who-Shall-Not-Be-Named ?

**Comment by bernie-simon** [comment] 2016-05-18 20:07
On May 18, 2016, at 4:01 PM, P. L. Lim <notifications@github.com> wrote:

> Yes, but I think this is @bernie-simon's turf?

Unless told otherwise, I am working on the 10 gigabyte wcs blowup problem in pyasdf (probably caused by modeling.) Sphere problems will be next.

**Comment by nden** [comment] 2016-05-18 20:10
May be @mcara can have a try at this (if he's waiting on it).

**Comment by mcara** [comment] 2016-05-18 20:29
@nden Thank you for your guidance

**Comment by bernie-simon** [comment] 2016-06-10 11:29
The fix has been merged, there is a test for the problem you reported (self-intersection) and it passes.

**Closed by bernie-simon** 2016-06-10 11:29 UTC
